[package]
name = "wasm_battle_arena"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_ggrs = { version = "0.13", features = ["wasm-bindgen"]}
ggrs = "0.9"
bevy_matchbox = { version = "0.7", features = ["ggrs"]}
bevy_asset_loader = "0.17"
bevy_roll_safe = { git = "https://github.com/johanhelsing/bevy_roll_safe" }

[patch.crates-io]
bevy = { git = "https://github.com/johanhelsing/bevy", branch = "reflect-states-0.11" }
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features=["bevy_reflect"]}
bevy_matchbox = { git = "https://github.com/johanhelsing/matchbox", branch = "main"}