[package]
name = "wasm_battle_arena"
version = "0.1.6"
edition = "2021"

[profile.release]
opt-level = 's'
lto = "thin"

[dependencies]
bevy = "0.11"
bevy_ggrs = { version = "0.13", features = ["wasm-bindgen"]}
ggrs = "0.9"
bevy_matchbox = { version = "0.7", features = ["ggrs"]}
bevy_asset_loader = { version = "0.17", features=["2d"]}
bevy_roll_safe = { git = "https://github.com/johanhelsing/bevy_roll_safe" }
bevy_egui = "0.22"
egui_plot = "0.23"
wasm-bindgen = "0.2.87"
seeded-random = "0.6"

[patch.crates-io]
bevy = { git = "https://github.com/johanhelsing/bevy", branch = "reflect-states-0.11" }
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features=["bevy_reflect"]}
bevy_matchbox = { git = "https://github.com/johanhelsing/matchbox", branch = "main"}

[features]
local = []